configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/dorado.smk"
include: "rules/align.smk"
include: "rules/flair.smk"
include: "rules/stringtie.smk"
include: "rules/novel.smk"
include: "rules/quant.smk"
include: "rules/diffexp.smk"
include: "rules/polya.smk"

onstart:
    print("\n--- NanoSeq Direct RNA-seq started ---\n")

onsuccess:
    print("\n--- Workflow finished! ---\n")

onerror:
    print("\n--- An error occurred! ---\n")

rule all:
    default_target: True
    input:
        pipeline_targets()
